/* =====================
    SEQUENCES
===================== */
CREATE SEQUENCE SQ_T_SMARTMOTTU_USUARIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_T_SMARTMOTTU_TIPO_MOTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_T_SMARTMOTTU_STATUS_MOTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_T_SMARTMOTTU_MOTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_T_SMARTMOTTU_ALUGUEL START WITH 1 INCREMENT BY 1;

/* =====================
    TABELAS
===================== */
CREATE TABLE T_SMARTMOTTU_STATUS_MOTO (
	id_status   BIGINT NOT NULL PRIMARY KEY DEFAULT NEXT VALUE FOR SQ_T_SMARTMOTTU_STATUS_MOTO,
	status      VARCHAR(50) NOT NULL,
	data        DATE NULL
);

CREATE TABLE T_SMARTMOTTU_TIPO_MOTO (
	id_tipo BIGINT NOT NULL PRIMARY KEY DEFAULT NEXT VALUE FOR SQ_T_SMARTMOTTU_TIPO_MOTO,
	nm_tipo VARCHAR(50) NOT NULL,
	CHECK (nm_tipo IN ('MOTTU_SPORT_110I','MOTTU_SPORT_ESD_2025','MOTTU_POP_100','MOTTU_POP_150','MOTTU_ELETRICA_X'))
);

CREATE TABLE T_SMARTMOTTU_USUARIO (
	id_usuario BIGINT NOT NULL PRIMARY KEY DEFAULT NEXT VALUE FOR SQ_T_SMARTMOTTU_USUARIO,
	nome       VARCHAR(80)  NOT NULL,
	email      VARCHAR(120) NOT NULL,
	senha      VARCHAR(255) NOT NULL,
	role       VARCHAR(20)  NOT NULL DEFAULT 'USER'
);

CREATE TABLE T_SMARTMOTTU_MOTO (
	id_moto      BIGINT NOT NULL PRIMARY KEY DEFAULT NEXT VALUE FOR SQ_T_SMARTMOTTU_MOTO,
	nm_chassi    VARCHAR(17) NOT NULL,
	placa        VARCHAR(7)  NOT NULL,
	unidade      VARCHAR(100) NULL,
	fk_id_status BIGINT NOT NULL,
	fk_id_tipo   BIGINT NOT NULL,
	fk_id_usuario BIGINT NULL,
	CONSTRAINT FK_MOTO_STATUS  FOREIGN KEY (fk_id_status)  REFERENCES T_SMARTMOTTU_STATUS_MOTO(id_status),
	CONSTRAINT FK_MOTO_TIPO    FOREIGN KEY (fk_id_tipo)    REFERENCES T_SMARTMOTTU_TIPO_MOTO(id_tipo),
	CONSTRAINT FK_MOTO_USUARIO FOREIGN KEY (fk_id_usuario) REFERENCES T_SMARTMOTTU_USUARIO(id_usuario)
);

CREATE TABLE T_SMARTMOTTU_ALUGUEL (
	id_aluguel    BIGINT NOT NULL PRIMARY KEY DEFAULT NEXT VALUE FOR SQ_T_SMARTMOTTU_ALUGUEL,
	fk_usuario_id BIGINT NOT NULL,
	fk_moto_id    BIGINT NOT NULL,
	data_inicio   DATE   NOT NULL,
	data_fim      DATE       NULL,
	valor_total   DECIMAL(10,2) NULL,
	status        VARCHAR(20) NOT NULL,
	CONSTRAINT FK_ALUGUEL_USUARIO FOREIGN KEY (fk_usuario_id) REFERENCES T_SMARTMOTTU_USUARIO(id_usuario),
	CONSTRAINT FK_ALUGUEL_MOTO    FOREIGN KEY (fk_moto_id)    REFERENCES T_SMARTMOTTU_MOTO(id_moto)
);


-- DADOS INICIAIS (SEED)
INSERT INTO T_SMARTMOTTU_STATUS_MOTO (status, data) VALUES ('ATIVO',       '2025-01-10');
INSERT INTO T_SMARTMOTTU_STATUS_MOTO (status, data) VALUES ('MANUTENCAO',  '2025-02-15');
INSERT INTO T_SMARTMOTTU_STATUS_MOTO (status, data) VALUES ('CANCELADO',   '2025-03-20');
INSERT INTO T_SMARTMOTTU_STATUS_MOTO (status, data) VALUES ('BLOQUEADO',   '2025-04-25');
INSERT INTO T_SMARTMOTTU_STATUS_MOTO (status, data) VALUES ('INATIVO',     '2025-05-30');
INSERT INTO T_SMARTMOTTU_STATUS_MOTO (status, data) VALUES ('ALUGADA',     '2025-06-02');

INSERT INTO T_SMARTMOTTU_TIPO_MOTO (nm_tipo) VALUES ('MOTTU_SPORT_110I');
INSERT INTO T_SMARTMOTTU_TIPO_MOTO (nm_tipo) VALUES ('MOTTU_SPORT_ESD_2025');
INSERT INTO T_SMARTMOTTU_TIPO_MOTO (nm_tipo) VALUES ('MOTTU_POP_100');
INSERT INTO T_SMARTMOTTU_TIPO_MOTO (nm_tipo) VALUES ('MOTTU_POP_150');
INSERT INTO T_SMARTMOTTU_TIPO_MOTO (nm_tipo) VALUES ('MOTTU_ELETRICA_X');

-- Usuário ADMIN 
INSERT INTO T_SMARTMOTTU_USUARIO (nome, email, senha, role) VALUES ('Administrador','admin@email.com','admin123','ADMIN');

-- Motos
INSERT INTO T_SMARTMOTTU_MOTO (nm_chassi, placa, unidade, fk_id_status, fk_id_tipo) VALUES ('9MCNSL953VV182782', 'HMK9012', 'Bras',   1, 1);
INSERT INTO T_SMARTMOTTU_MOTO (nm_chassi, placa, unidade, fk_id_status, fk_id_tipo) VALUES ('1PSCNS391DX139403', 'LPS0292', 'Butanta', 1, 2);
INSERT INTO T_SMARTMOTTU_MOTO (nm_chassi, placa, unidade, fk_id_status, fk_id_tipo) VALUES ('5MDPEM424SD029432', 'MSK2145', 'Carrao',  2, 1);
INSERT INTO T_SMARTMOTTU_MOTO (nm_chassi, placa, unidade, fk_id_status, fk_id_tipo) VALUES ('9BWZZZ377VT004252', 'KSH2323', 'Lapa',    2, 2);