-- V1 - Remoção de objetos (SQL Server)
IF OBJECT_ID('T_SMARTMOTTU_MOTO','U') IS NOT NULL DROP TABLE T_SMARTMOTTU_MOTO;
IF OBJECT_ID('T_SMARTMOTTU_STATUS_MOTO','U') IS NOT NULL DROP TABLE T_SMARTMOTTU_STATUS_MOTO;
IF OBJECT_ID('T_SMARTMOTTU_TIPO_MOTO','U') IS NOT NULL DROP TABLE T_SMARTMOTTU_TIPO_MOTO;
IF OBJECT_ID('T_SMARTMOTTU_USUARIO','U') IS NOT NULL DROP TABLE T_SMARTMOTTU_USUARIO;

-- Sequences (caso existam)
IF OBJECT_ID('SQ_T_SMARTMOTTU_MOTO','SO') IS NOT NULL DROP SEQUENCE SQ_T_SMARTMOTTU_MOTO;
IF OBJECT_ID('SQ_T_SMARTMOTTU_STATUS_MOTO','SO') IS NOT NULL DROP SEQUENCE SQ_T_SMARTMOTTU_STATUS_MOTO;
IF OBJECT_ID('SQ_T_SMARTMOTTU_TIPO_MOTO','SO') IS NOT NULL DROP SEQUENCE SQ_T_SMARTMOTTU_TIPO_MOTO;
IF OBJECT_ID('SQ_T_SMARTMOTTU_USUARIO','SO') IS NOT NULL DROP SEQUENCE SQ_T_SMARTMOTTU_USUARIO;