-- V2 - Criação de sequences e tabelas (SQL Server)
CREATE SEQUENCE SQ_T_SMARTMOTTU_USUARIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_T_SMARTMOTTU_TIPO_MOTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_T_SMARTMOTTU_STATUS_MOTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_T_SMARTMOTTU_MOTO START WITH 1 INCREMENT BY 1;

CREATE TABLE T_SMARTMOTTU_USUARIO (
    id_usuario BIGINT NOT NULL PRIMARY KEY DEFAULT NEXT VALUE FOR SQ_T_SMARTMOTTU_USUARIO,
    nome VARCHAR(80) NOT NULL,
    email VARCHAR(120) NOT NULL,
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE T_SMARTMOTTU_TIPO_MOTO (
    id_tipo BIGINT NOT NULL PRIMARY KEY DEFAULT NEXT VALUE FOR SQ_T_SMARTMOTTU_TIPO_MOTO,
    nm_tipo VARCHAR(50) NOT NULL
);

CREATE TABLE T_SMARTMOTTU_STATUS_MOTO (
    id_status BIGINT NOT NULL PRIMARY KEY DEFAULT NEXT VALUE FOR SQ_T_SMARTMOTTU_STATUS_MOTO,
    status VARCHAR(50) NOT NULL,
    data DATE NULL
);

CREATE TABLE T_SMARTMOTTU_MOTO (
    id_moto BIGINT NOT NULL PRIMARY KEY DEFAULT NEXT VALUE FOR SQ_T_SMARTMOTTU_MOTO,
    nm_chassi VARCHAR(17) NOT NULL,
    placa VARCHAR(7) NOT NULL,
    unidade VARCHAR(100) NULL,
    fk_id_status BIGINT NOT NULL,
    fk_id_tipo BIGINT NOT NULL
);