-- V3 - Constraints (SQL Server)
ALTER TABLE T_SMARTMOTTU_MOTO
   ADD CONSTRAINT FK_MOTO_STATUS
   FOREIGN KEY (fk_id_status)
   REFERENCES T_SMARTMOTTU_STATUS_MOTO(id_status);

ALTER TABLE T_SMARTMOTTU_MOTO
   ADD CONSTRAINT FK_MOTO_TIPO
   FOREIGN KEY (fk_id_tipo)
   REFERENCES T_SMARTMOTTU_TIPO_MOTO(id_tipo);